import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://elyp.intechsol-pr.net/Login/Index');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('migueltorres@demo.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Intechsol2025');
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.getByRole('link', { name: 'Resources Administration' }).click();
  await page.getByRole('columnheader', { name: 'Column Settings Last Name' }).getByLabel('Column Settings').click();
  await page.locator('div').filter({ hasText: 'IDFull NameFirst NameLast' }).first().click();
  await page.getByRole('link', { name: 'imageAdd New Employee' }).click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('C');
  await page.getByRole('textbox', { name: 'Last Name*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Car');
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Carlos');
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('roberto');
  await page.getByRole('textbox', { name: 'First Name*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name*' }).fill('oberto');
  await page.getByRole('textbox', { name: 'First Name*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Roberto');
  await page.getByRole('textbox', { name: 'First Name*' }).press('CapsLock');
  await page.locator('#EmpPostalAddress').click();
  await page.locator('#EmpPostalAddress').press('CapsLock');
  await page.locator('#EmpPostalAddress').fill('C');
  await page.locator('#EmpPostalAddress').press('CapsLock');
  await page.locator('#EmpPostalAddress').fill('Calle de la estrella ');
  await page.locator('#EmpPostalZipCode').click();
  await page.locator('#EmpPostalZipCode').fill('28032-20202_____-____');
  await page.getByText('Save', { exact: true }).click();
  await page.locator('div:nth-child(2) > span > .k-dropdown-wrap > .k-input').first().click();
  await page.getByRole('option', { name: 'Aguada' }).click();
  await page.locator('#EmpAddress').click();
  await page.locator('#EmpAddress').fill('Calle de la estrella 1');
  await page.locator('#EmpZipCode').click();
  await page.locator('#EmpZipCode').fill('11111-11111_____-____');
  await page.locator('div:nth-child(5) > span > .k-dropdown-wrap > .k-input').first().click();
  await page.getByRole('option', { name: 'Aguada' }).click();
  await page.locator('#ApplicantPersonalInfo div').filter({ hasText: 'Postal Address is Primary' }).nth(4).click({
    button: 'middle'
  });
  await page.getByRole('textbox', { name: 'Home' }).click();
  await page.getByRole('textbox', { name: 'Home' }).fill('(111) 111-1111_');
  await page.getByRole('textbox', { name: 'Email Address*' }).click();
  await page.getByRole('textbox', { name: 'Email Address*' }).fill('hola@gmail.com');
  await page.getByRole('textbox', { name: 'Email Address*' }).press('CapsLock');
  await page.getByRole('combobox', { name: 'Birth Date*' }).click();
  await page.getByRole('button', { name: 'select' }).nth(1).click();
  await page.getByTitle('Tuesday, June 10,').click();
  await page.getByRole('textbox', { name: 'Social Security*' }).click();
  await page.getByRole('textbox', { name: 'Social Security*' }).fill('111-11-11111');
  await page.locator('#ApplicantPersonalInfo').click();
  await page.locator('.form-group > div:nth-child(3) > span > .k-dropdown-wrap > .k-input').first().click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByRole('link', { name: 'SETTINGS ' }).click();
  await page.getByRole('combobox', { name: 'Hire Date*' }).click();
  await page.getByRole('button', { name: 'select' }).click();
  await page.locator('#EmpHireDate_dateview').getByTitle('Tuesday, June 10,').click();
  await page.locator('div:nth-child(4) > div:nth-child(2) > span > .k-dropdown-wrap > .k-input').first().click();
  await page.locator('div:nth-child(4) > div:nth-child(2) > span > .k-dropdown-wrap > .k-input').first().click();
  await page.getByRole('option', { name: 'Part-Time' }).click();
  await page.getByRole('listbox', { name: 'Profile*' }).locator('span').nth(1).click();
  await page.getByRole('option', { name: 'ExternalApplicant' }).click();
  await page.locator('div:nth-child(3) > div:nth-child(2) > .col-md-8 > span > .k-dropdown-wrap > .k-input').click();
  await page.getByRole('option', { name: '3 EXEMPT SP PAY' }).click();
  await page.locator('div:nth-child(6) > .col-md-8 > span > .k-dropdown-wrap > .k-input').first().click();
  await page.getByRole('option', { name: 'Monthly' }).click();
  await page.locator('.col-md-4 > div:nth-child(5) > .col-md-8 > .k-widget > .k-dropdown-wrap > .k-input').click();
  await page.getByRole('option', { name: '0068-000 Servicios Médicos y' }).click();
  await page.getByRole('listbox', { name: 'Cost Center' }).locator('span').nth(1).click();
  await page.getByRole('option', { name: 'Cost Center 2' }).click();
  await page.getByRole('listbox', { name: 'Payment Type*' }).locator('span').nth(1).click();
  await page.getByRole('listbox', { name: 'Payment Type*' }).locator('span').nth(1).click();
  await page.getByRole('option', { name: 'Check' }).click();
  await page.getByRole('link', { name: 'CUSTOM FIELDS ' }).click();
  await page.getByRole('link', { name: 'PERSONAL INFORMATION ' }).click();
  await page.getByRole('link', { name: 'PERSONAL INFORMATION ' }).click();
  await page.getByRole('link', { name: 'SETTINGS ' }).click();
  await page.locator('#TimeAttPayrollInfo').getByText('Monthly').click();
});